#!/usr/bin/env bash

set -e

# follow link
CLI_PATH=$0
if [[ -n $(readlink $CLI_PATH) ]]; then
  CLI_PATH=$(readlink $CLI_PATH)
fi
CLI_WORKDIR=$(dirname $CLI_PATH)

cli_help() {
  cli_name=$(basename $CLI_PATH)
  echo "
$cli_name
Enviroment Setuper (theme, terminal, dotfiles etc)
Version: $(cat $CLI_WORKDIR/VERSION)
Usage: $cli_name [command]
Commands:
  test
  zsh
  neovim
  terminal
  system
  *         Help
"
  exit 1
}

case "$1" in
  test|t)
    $CLI_WORKDIR/commands/test ${@:2}
    ;;
  zsh)
    $CLI_WORKDIR/commands/zsh ${@:2}
    ;;
  neovim)
    $CLI_WORKDIR/commands/neovim ${@:2}
    ;;
  terminal)
    $CLI_WORKDIR/commands/terminal ${@:2}
    ;;
  system)
    $CLI_WORKDIR/commands/system ${@:2}
    ;;
  all)
    $CLI_WORKDIR/commands/system all
    $CLI_WORKDIR/commands/terminal all
    $CLI_WORKDIR/commands/neovim all
    $CLI_WORKDIR/commands/zsh all
  *)
    cli_help
    ;;
esac
