#!/usr/bin/env bash

LANGAUGES="python nodejs go rust"

cli_help() {
  echo "
Command: asdf [install | list | languages | python | node | go | rust | all]
Usage:
  install    -> install asdf
  list       -> list programming languages that will be installed
  languages  -> install the programming languages
  python     -> install python
  node       -> install node
  go         -> install go
  rust       -> install rust
  all        -> run all commands above"
  exit 1
}

asdf_install() {
  echo "Installing asdf"
	sudo wget --output-document=/tmp/asdf.tar.gz https://github.com/asdf-vm/asdf/releases/download/v0.16.1/asdf-v0.16.1-linux-amd64.tar.gz
  tar -xvf /tmp/asdf.tar.gz --directory=/tmp
  sudo mv /tmp/asdf /usr/bin
  echo "asdf installed"
}

asdf_install_python() {
  sudo apt install -y libpq-dev libffi-dev libncurses5-dev zlib1g zlib1g-dev libssl-dev libreadline-dev libbz2-dev libsqlite3-dev liblzma-dev

  asdf plugin add python https://github.com/asdf-community/asdf-python || true
  PYTHON_VERSION=$(asdf list all python | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+" | grep -v "[a-zA-Z]" | tail -n 1)
  asdf install python $PYTHON_VERSION
  asdf set -u python $PYTHON_VERSION
}

asdf_install_rust() {
  asdf plugin add rust https://github.com/code-lever/asdf-rust.git || true
  RUST_VERSION=$(asdf list all rust | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+" | grep -v "[a-zA-Z]" | tail -n 1)
  asdf install rust $RUST_VERSION
  asdf set -u rust $RUST_VERSION
 }

asdf_install_node() {
	asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git || true
	NODE_VERSION=$(asdf list all nodejs | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+" | grep -v "[a-zA-Z]" | tail -n 1)
	asdf install nodejs $NODE_VERSION
	asdf set -u nodejs $NODE_VERSION
}

asdf_install_golang() {
  asdf plugin add golang https://github.com/kennyp/asdf-golang.git || true
	GOLANG_VERSION=$(asdf list all golang | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+" | grep -v "[a-zA-Z]" | tail -n 1)
	asdf install golang $GOLANG_VERSION
	asdf set -u golang $GOLANG_VERSION

  go install golang.org/x/tools/gopls@latest
}

asdf_list() {
  echo $LANGAUGES
}

asdf_install_languages() {
  asdf_install_python
  asdf_install_node
  asdf_install_golang
  asdf_install_rust
}

[ ! -n "$1" ] && cli_help && exit 1

case "$1" in
  install)
    asdf_install
    ;;
  list)
    asdf_list_languages
    ;;
  languages)
    asdf_install_languages
    ;;
  python)
    asdf_install_python
    ;;
  rust)
    asdf_install_rust
    ;;
  go)
    asdf_install_golang
    ;;
  node)
    asdf_install_node
    ;;
  all)
    asdf_install
    asdf_list
    asdf_install_languages
    ;;
  *)
    cli_help
    ;;
esac
