#!/usr/bin/env bash

set -e

NEOVIM_DIR="/opt/nvim"

cli_help() {
  echo "
Command: neovim [install | dotfiles]
Usage:
  setuper neovim install  -> install latest neovim version
  setuper neovim dotfiles -> setup dotfiles and install plugins
  setuper neovim all      -> run all commands above"
}

# required library to open appimages
fuse_install() {
	echo "Installing fuse (required for open neovim appimage)"
	sudo add-apt-repository -y universe
	sudo apt install -y libfuse2
}

neovim_install() {
	echo "Installing neovim"
	fuse_install
	echo "Downloading neovim"
	sudo mkdir -p $NEOVIM_DIR
	sudo wget --quiet --output-document=$NEOVIM_DIR/nvim.appimage https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
	sudo chmod 755 $NEOVIM_DIR
	sudo chmod +x $NEOVIM_DIR/nvim.appimage
	sudo ln -s -T $NEOVIM_DIR/nvim.appimage /usr/bin/nvim
	echo "Neovim installed"
}

neovim_dotfiles() {
	echo "Setting up neovim dotfiles"
	# dotfiles
	ln -s -T /srv/dotfiles/nvim $XDG_CONFIG_HOME/nvim

	# plugins manager
	if [[ -z "$XDG_DATA_HOME" ]]; then
		echo "XDG_DATA_HOME not configured"
		exit 1
	fi
	
	echo "Installing neovim plugin manager"
	mkdir -p ~/.config
	sudo ln -s ~/.dotfiles/nvim/ ~/.config/nvim 2> /dev/null
	git clone --depth=1 https://github.com/savq/paq-nvim.git \
	 $XDG_DATA_HOME/nvim/site/pack/paqs/start/paq-nvim || true
	echo "Installing neovim plugins"
	nvim --headless +PaqInstall +q	
}

[ ! -n "$1" ] && cli_help

case "$1" in
  install)
	  neovim_install
    ;;
  dotfiles)
	neovim_dotfiles
	;;
  all)
  	neovim_install
  	neovim_dotfiles
  	echo "Neovim all done"
  	;;
  *)
    cli_help
    ;;
esac
