#!/usr/bin/env bash

set -e

PACKAGES='git curl build-essential vim snapd libssl-dev libpq-dev libpam-gnome-keyring xclip'
PROGRAMS='docker'

cli_help() {
  echo "
Command: system [appearance | programs | all]
Usage:
  list       -> list programs to be installed by the 'programs' command
  packages        -> install basic apt packages
  docker     -> donwload and setup docker
  all        -> run all commands above"
  exit 1
}

docker_install() {
	echo "Installing docker"
	sudo apt install -y ca-certificates curl gnupg lsb-release
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor --batch --yes -o /usr/share/keyrings/docker-archive-keyring.gpg
	echo \
	  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
	  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
	sudo apt update
	sudo apt install -y docker-ce docker-ce-cli containerd.io
	sudo groupadd -f docker
	sudo usermod -aG docker $USER
  echo "Docker installed"

}

packages_install() {
  echo "Installing packages"
  sudo apt update -y
  sudo apt install -y $PACKAGES
  echo "Packages installed"
}

programs_list() {
  echo "APT packages to be installed:"
  echo $PACKAGES
  echo "Other programs to be installed:"
  echo $PROGRAMS
}

[ ! -n "$1" ] && cli_help

case "$1" in
  list)
    programs_list
    ;;
  packages)
    packages_install
    ;;
  docker)
    docker_install
    ;;
  all)
    programs_list
    packages_install
    docker_install
    ;;
  *)
    cli_help
    ;;
esac
