#!/usr/bin/env bash


cli_help() {
  echo "
Command: system [font | theme | dock | all]
Usage:
  font       -> download and configure Hack font
  theme      -> setup icons and theme
  dock       -> setup dock
  all        -> run all commands above"
  exit 1
}

icon_theme_setup() {
  if [[ -z $(ls /usr/share/icons | grep "candy-icons") ]]; then
  wget 'https://github.com/EliverLara/candy-icons/archive/refs/heads/master.zip' -O /tmp/candy-icons.zip
    sudo unzip /tmp/candy-icons.zip -d /usr/share/icons/
  fi
  gsettings set org.gnome.desktop.interface icon-theme candy-icons-master
}

system_theme_setup() {
  if [[ -z $(ls /usr/share/themes | grep -i "sweet") ]]; then
  wget 'https://github.com/EliverLara/Sweet/releases/download/v3.0/Sweet-Dark-v40.zip' -O /tmp/sweet-theme.zip
    sudo unzip /tmp/sweet-theme.zip -d /usr/share/themes/
  fi
	gsettings set org.gnome.desktop.interface gtk-theme 'Sweet-Dark-v40'
	gsettings set org.gnome.desktop.wm.preferences theme 'Sweet-Dark-v40'
}

# Download Hack font
fonts_download() {
  if [[ -z $(ls /usr/share/fonts/ttf | grep -i "hack") ]]; then
    sudo mkdir -p /usr/share/fonts/ttf
  wget 'https://github.com/source-foundry/Hack/releases/download/v3.003/Hack-v3.003-ttf.zip' -O /tmp/hack-font.zip
    sudo unzip /tmp/hack-font.zip -d /tmp/hack-font/
    sudo cp -t /usr/share/fonts/ttf/ /tmp/hack-font/ttf/*
  fi

  if [[ -z $(ls /usr/share/fonts | grep -i "firacode") ]]; then
    sudo mkdir -p /usr/share/fonts
    wget --output-document=/tmp/firacode.zip https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip
    sudo unzip /tmp/firacode.zip -d /tmp/firacode/
    sudo cp -t /usr/share/fonts/ /tmp/firacode/ttf/*
  fi

  if [[ -z $(ls /usr/share/fonts | grep -i "nerdfontssymbolsonly") ]]; then
    sudo mkdir -p /usr/share/fonts
    wget --output-document=/tmp/NerdFontsSymbolsOnly.zip https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/NerdFontsSymbolsOnly.zip
    sudo unzip /tmp/NerdFontsSymbolsOnly.zip -d /tmp/NerdFontsSymbolsOnly
    sudo cp -t /usr/share/fonts/ /tmp/NerdFontsSymbolsOnly/SymbolsNerdFontMono-Regular.ttf /tmp/NerdFontsSymbolsOnly/SymbolsNerdFont-Regular.ttf
  fi

  fc-cache -f -v
}

fonts_setup() {
  fonts_download
	gsettings set org.gnome.desktop.interface font-name 'Hack Regular 12'
}

dock_setup() {
	gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed 'false'
	gsettings set org.gnome.shell.extensions.dash-to-dock autohide 'true'
	gsettings set org.gnome.shell.extensions.dash-to-dock intellihide 'true'
	gsettings set org.gnome.shell.extensions.dash-to-dock extend-height 'false'
}

setup_apprearance() {
  icon_theme_setup
  system_theme_setup
  fonts_setup
  dock_setup
}

[ ! -n "$1" ] && cli_help

case "$1" in
  font)
    fonts_setup
    ;;
  theme)
    icon_theme_setup
    system_theme_setup
    ;;
  dock)
    dock_setup
    ;;
  all)
    fonts_setup
    icon_theme_setup
    system_theme_setup
    dock_setup
    ;;
  *)
    cli_help
    ;;
esac
