#!/usr/bin/env bash

set -e

# Dracula theme colors
BACKGROUND="#282A36"
CURRENT_LINE="#44475A"
FOREGROUND="#F8F8F2"
WHITE="#F8F8F2"
COMMENT="#6272A4"
CYAN="#8BE9FD"
GREEN="#50FA7B"
ORANGE="#FFB86C"
PINK="#FF79C6"
PURPLE="#BD93F9"
RED="#FF5555"
YELLOW="#F1FA8C"
# Not from dracula
GRAY="#2E3436"
BLUE="#5D7BE6"
# Changes default terminal color palette
# black, red, green, yellow, blue, purple, cyan, white
PALETTE="[$GRAY, $RED, $GREEN, $YELLOW, $BLUE, $PURPLE, $CYAN, $WHITE, 'rgb(76,76,76)', 'rgb(255,0,0)', 'rgb(0,255,0)', 'rgb(255,255,0)', 'rgb(70,130,180)', 'rgb(255,0,255)', 'rgb(0,255,255)', 'rgb(255,255,255)']"
DEFAULT_SYSTEM_PALETTE="['#171421', '#c01c28', '#26a269', '#a2734c', '#12488b', '#a347ba', '#2aa1b3', '#d0cfcc', '#5e5c64', '#f66151', '#33da7a', '#e9ad0c', '#2a7bde', '#c061cb', '#33c7de', '#ffffff']"

cli_help() {
  echo "
Setup terminal fonts and colors
Command: terminal [setup]
Usage:
  setuper terminal setup -> donwload fonts and setup fonts and colors"
}

# Donwload FiraCode font
fonts_donwload() {
  if [[ -z $(ls /usr/share/fonts | grep -i "firacode") ]]; then
    sudo mkdir -p /usr/share/fonts
    wget --output-document=/tmp/firacode.zip https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip
    sudo unzip /tmp/firacode.zip -d /tmp/firacode/
    sudo cp -t /usr/share/fonts/ /tmp/firacode/ttf/*
  fi
}

terminal_setup() {
  fonts_donwload

  # From: https://askubuntu.com/questions/1141782/how-to-change-the-background-of-the-terminal-through-a-command
	DEFAULT_PROFILE=$(gsettings get org.gnome.Terminal.ProfilesList default)
	PROFILE_ID=$(echo "$DEFAULT_PROFILE" | cut -d "'" -f 2)
	gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$PROFILE_ID/ use-theme-colors false
  gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$PROFILE_ID/ palette $PALETTE 2> /dev/null || true
  gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$PROFILE_ID/ foreground-color $WHITE 2> /dev/null || true
  gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$PROFILE_ID/ background-color "'$BACKGROUND'"
	gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$PROFILE_ID/ use-system-font false
	gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$PROFILE_ID/ font 'Fira Code Medium 14'
}

[ ! -n "$1" ] && cli_help

case "$1" in
  setup)
    terminal_setup
    ;;
  *)
    cli_help
    ;;
esac
