#!/usr/bin/env bash

set -e
. "$CLI_WORKDIR/common"

cli_help_test() {
  echo "Command: setuper test <text>
Usage:
  test <text>      Log the <text>
  *                Help
"
}

[ -z "$1" ] && cli_help_test && exit 0

cli_log "$@"
