#!/usr/bin/env bash

set -e

cli_help_test() {
  echo "
Command: test <anything>
Usage:
  test <anything>      Print the <anything>
  *                    Help"
  exit 1
}

[ ! -n "$1" ] && cli_help_test

echo $@
